=== kituu02/sem/Week5/food.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT foodlist (fooditem+)>
<!ELEMENT fooditem (name,cost)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ATTLIST fooditem type (Italian|American|Russian) "American">

=== kituu02/sem/Web/Week5/food.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE foodlist SYSTEM "food.dtd">
<?xml-stylesheet type="text/xsl" href="food.xsl"?>
<foodlist>
    <fooditem type="Italian">
        <name>Pizza</name>
        <cost>$10</cost>
    </fooditem>
    <fooditem type="Italian">
        <name> Pasta</name>
        <cost>$5</cost>
    </fooditem>
    <fooditem type="American">
        <name>Burger</name>
        <cost>$8</cost>
    </fooditem>
    <fooditem type="Russian">
        <name>Noodles</name>
        <cost>$9</cost>
    </fooditem>
    <fooditem  type="Russian">
        <name>Noodles</name>
        <cost>$9</cost>
    </fooditem>
</foodlist>
